name: simulation
root: ./
startup_window: status
windows:
  - roscore:
      layout: tiled
      panes:
        - roscore
#  - rqt_imgs:
#      layout: tiled
#      panes:
#        - waitForRos; rosrun rqt_image_view rqt_image_view /$UAV_NAME/fleft/tag_detections_image
#        - waitForRos; rosrun rqt_image_view rqt_image_view /$UAV_NAME/fright/tag_detections_image
  - rviz:
      layout: tiled
      panes:
        - waitForRos; rviz -d $(rospack find basler_stereopair_driver)/rviz/calibration.rviz
  - pylon_camera_driver:
      layout: tiled
      panes:
        - waitForRos; roslaunch pylon_camera morhunenko.launch
  - basler_stereo_driver:
      layout: tiled
      panes:
        - waitForRos; roslaunch basler_stereopair_driver basler_stereopair_driver.launch is_calibrated:=false calib_algo:="PnP"