image_width: 1600
image_height: 1200
camera_name: basler_left
camera_matrix:
  rows: 3
  cols: 3
  data: [815.5976 ,   0.     , 796.87741,
         0.     , 812.26899, 584.6144 ,
         0.     ,   0.     ,   1.     ]
distortion_model: rational_polynomial
distortion_coefficients:
  rows: 1
  cols: 8
  data: [0.226098, -0.014013, 0.000106, -0.000117, 0.000654, 0.639590, 0.000000, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [265.03693,   0.     , 791.59648,   0.     ,
         0.     , 264.4697 , 581.13779,   0.     ,
         0.     ,   0.     ,   1.     ,   0.     ]
