fright_camera:
  rotation: [ -0.709,  -0.011,   0.706,
              -0.706, 0.00478,  -0.709,
              0.00445,      -1, -0.0112 ]
  translation: [ 0.0851,
                 -0.062,
                 0.00298 ]
