fleft_camera:
  rotation: [ 0.714,  0.00671,      0.7,
              -0.7,   0.0118,    0.714,
              -0.00348,       -1,   0.0131 ]
  translation: [ 00703,
                 0.0611,
                 -0.00676 ]
